Models/Contacto.cs
namespace Practica08.Models
{
    public class Contacto
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Practica08.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/ContactoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Practica08.Models;

namespace Practica08.Controllers
{
    public class ContactoController : Controller{
       private readonly ILogger<ContactoController> _logger;

        public ContactoController(ILogger<ContactoController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contacto objContacto)
        {
            ViewData["Message"]="Se registro el contacto";
            return View("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Practica08.Models;

namespace Practica08.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProductosServicios()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Contacto/Index.cshtml
@model Contacto

<form asp-controller="Contacto" asp-action="Create">
    <label asp-for="FirstName" class="control-label"></label>
    <input asp-for="FirstName" class="form-control"/>

    <label asp-for="LastName" class="control-label"></label>
    <input asp-for="LastName" class="form-control"/>

    <label asp-for="Email" class="control-label"></label>
    <input asp-for="Email" class="form-control"/>

    <label asp-for="Phone" class="control-label"></label>
    <input asp-for="Phone" class="form-control"/>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Registrar</button>
    </div>

</form>
<h1>@ViewData["Message"]</h1>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido "LA PIRAÑA"</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores ex consequatur doloribus accusantium iste eaque. Libero architecto modi nostrum, temporibus, vitae dignissimos deleniti ab officiis dolorem, explicabo similique soluta dolorum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores ex consequatur doloribus accusantium iste eaque. Libero architecto modi nostrum, temporibus, vitae dignissimos deleniti ab officiis dolorem, explicabo similique soluta dolorum?Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores ex consequatur doloribus accusantium iste eaque. Libero architecto modi nostrum, temporibus, vitae dignissimos deleniti ab officiis dolorem, explicabo similique soluta dolorum?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores ex consequatur doloribus accusantium iste eaque. Libero architecto modi nostrum, temporibus, vitae dignissimos deleniti ab officiis dolorem, explicabo similique soluta dolorum?</p>
</div>

Views/Home/ProductosServicios.cshtml
@{
    ViewData["Title"] = "Productos y Servicios";
}

<h1 align="center">@ViewData["Title"]</h1>
<br>
<br>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestias, nostrum accusantium non quas dignissimos quos culpa, sint sed et perferendis cumque quis? Blanditiis consectetur quia quas aspernatur. Neque, rerum recusandae.</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Practica08</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Practica08</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Quiénes Somos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ProductosServicios">Servicios y Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Practica08 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>